### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by ftuyama** [justgigio/awesome-git-mosaic#1]
Where is the code, bro? Can you provide us with a screenshot?

**Comment by justgigio** [comment]
I'm working on it! Had several home tasks to do and less time to code for fun lately. But it's almost done. I can already convert strings to "pixels" and output in console:
![image](https://user-images.githubusercontent.com/698586/81831376-a5650600-9513-11ea-9f0c-a2ff23adb2ec.png)

I can convert (x, y) positions to corresponding timestamp that will be in place into Git mosaic (0, 0) is top left (one year ago).
All i still have to do is tie them together.
All with 100% test coverage 😉

**Comment by justgigio** [comment]
Also, @ftuyama, miss you, guy! <3
